//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtOrganization()
        {
            this.Showings = new HashSet<Showing>();
        }
    
        public int IDOrganization { get; set; }
        public Nullable<decimal> ComfortabilityRating { get; set; }
        public string Website { get; set; }
        public string WorkHours { get; set; }
        public string IDPicture { get; set; }
        public Nullable<int> IDBuilding { get; set; }
        public string Name { get; set; }
        public string OrganizationType { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showing> Showings { get; set; }
    }
}
