//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen_Sensor
    {
        public int IDString { get; set; }
        public Nullable<int> IDCitizen { get; set; }
        public Nullable<int> IDSensor { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
