//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cook_Restaurant
    {
        public int IDSrting { get; set; }
        public Nullable<int> IDCook { get; set; }
        public Nullable<int> IDRestaurant { get; set; }
    
        public virtual FamousCook FamousCook { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
