//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Buildings = new HashSet<Building>();
            this.ObjectHasObjects = new HashSet<ObjectHasObject>();
            this.ObjectHasObjects1 = new HashSet<ObjectHasObject>();
        }
    
        public int IDOdject { get; set; }
        public string ObjectType { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string IDPicture { get; set; }
        public int IDSensor { get; set; }
        public string IDDocument { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual Sensor Sensor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectHasObject> ObjectHasObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectHasObject> ObjectHasObjects1 { get; set; }
    }
}
