//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectHasObject
    {
        public int IDString { get; set; }
        public int IDObjectParent { get; set; }
        public int IDObjectChild { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual Object Object1 { get; set; }
    }
}
