//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Cook_Restaurant = new HashSet<Cook_Restaurant>();
            this.Restaurant_Dish = new HashSet<Restaurant_Dish>();
        }
    
        public int IDOrganization { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<decimal> AverageCheck { get; set; }
        public Nullable<int> NumberOfEmptyTables { get; set; }
        public Nullable<int> IDFamousCook { get; set; }
        public Nullable<int> IDFanciestDish { get; set; }
        public Nullable<int> IDMostPopularDish { get; set; }
        public string Website { get; set; }
        public string IDPicture { get; set; }
        public string WorkHours { get; set; }
        public Nullable<int> IDBuilding { get; set; }
        public string Name { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cook_Restaurant> Cook_Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Dish> Restaurant_Dish { get; set; }
    }
}
