//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Dish
    {
        public int IDString { get; set; }
        public Nullable<int> IDRestaurant { get; set; }
        public Nullable<int> IDDish { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
