//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showing
    {
        public int IDShowing { get; set; }
        public Nullable<int> IDOrganization { get; set; }
        public Nullable<int> IDEvent { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DateTimeEvent { get; set; }
    
        public virtual ArtOrganization ArtOrganization { get; set; }
        public virtual Event Event { get; set; }
    }
}
