//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCityDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartCityEntities : DbContext
    {
        public SmartCityEntities()
            : base("name=SmartCityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtOrganization> ArtOrganizations { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Building_Citizen> Building_Citizen { get; set; }
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<Citizen_Sensor> Citizen_Sensor { get; set; }
        public virtual DbSet<Cook_Restaurant> Cook_Restaurant { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FamousCook> FamousCooks { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<ObjectHasObject> ObjectHasObjects { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Restaurant_Dish> Restaurant_Dish { get; set; }
        public virtual DbSet<Sensor> Sensors { get; set; }
        public virtual DbSet<Showing> Showings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
